name: check

on: push

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: yarn

      - name: Tests
        run: yarn test:ci
        env:
            FORCE_COLOR: true
      
      - name: Lint
        run: yarn lint